name: saving_girlfriend
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  http: ^1.2.1
  cupertino_icons: ^1.0.8
  device_preview: ^1.2.0
  go_router: ^15.1.2
  intl: ^0.20.2
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  uuid: ^4.5.1
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1
  flutter_glitter_effect: 1.0.3
  audioplayers: ^6.5.1
  path_provider: ^2.1.2
  path: ^1.9.0
  drift: ^2.28.0
  sqlite3_flutter_libs: ^0.5.22

dev_dependencies:
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.9
  flutter_lints: ^2.0.0
  drift_dev: ^2.28.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/background/
    - assets/images/character/
    - assets/images/icon/
    - assets/audio/bgm/
    - assets/audio/se/
    

    